sudo: false
language: scala
scala:
- 2.11.11
- 2.12.3
script:
- sbt ++$TRAVIS_SCALA_VERSION coverage test
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
after_success:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
  fi
- sbt coverageReport coveralls
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
env:
  global:
  - secure: t+sNfdVfNg2isAjLWUIOndcyYjap4aaTTOlxGnWXuLYMj9Io2wXo3BdC80vIEPo63WD2ewXFkW18L/4CeMhDglo+IR1Y7pJjA34ll4LoIWhcr+zEaMuGf5fB4ZyqUzMimCcvF8LbnQsKRGSIAmhgYqIgBmGnq4QXHg2NnmCbd2mKXrD4r7RwTndnXa/VwmoqHYMnUakPX0jwdFD1j0yXN+QXPDn3sTjUlXLeKCteiuZyLBsYA1CpA6y0Nlc1M8CI+cyIizXrodSq5TMMijvT6fLmhxPXLFjCsHOkiwVQlwP3gUGnx6rCxMRDFwY2klXvy76gJVnMbisMhXqC992njXuITLGnuckRPb3bLUwEauW86CA5DRsMRIsxJMeJjN3do9A4tA/vCok9gCj5F0+5WyPHpUCqjhHUy/4U10lAXT+uwIAtX/3cQt8n3fxg0GzdXMeNtaXMIDJwW5Ooh3gIcKvMxwVWWQMLPxtoQXCWknK78QB43djCm04yQkCl5VtYmusTSeTHBaHfvxW1wjc0uap1cKCOoEGEn82nKgWfLwWPi+i72DYwsoWhe+ROLm0u0pBpDZFJXyAhEw1+KsN8pwuzaGxP7skX0nNIP+UCFE0w8A0WK39PCRYNwdt12FhhrnsoC8RP5rK70246NaRRD7lgZHdn36/xToIHHsZa4SI=
  - secure: sCWfuRIRdT2enXitfOINy1buZOpCHC/kypcQ8HvoUD5rEwAfRGp3LF2YUKTma3sxu+BMAymyqBdJFHXxu4xsh7iXjRLvaKdW4RMxavDE8aS5ihlpJdak4U4/M6G9VJ8mAW9Q3EkQ3JgBSOyrIsx4YqvMf4+QLUKjyfitYfjDNuzW8ia7TPjs1ZYTKG9Q1HdB5b3VA4GfIptScDS2Xk+2pRYKSwtGwlU3znlGpeR6ALX/TJbticBUs7VMPQ54wHngyMY9P8i3Alxk3q6xESKbS5Z33cpbKT/iZnpjY5LuvSEPSejGjkZplZBSQpcN6E+2XAOZX2tosy5N35FckQWiEHBRxlx5wlWSfdez41yXCdo9r/HyCfoi8p9/Vf/PLH6KI5MN08DAzD2diQkd/XL+UqLz1KPe9VghdgB298H9BVFrjcyd1PjoeY/pJ6h8j2W56S61u/t6xlAbEGxMWZqqPORLTG5IJKcvahwYAXJsfLgEGOlqv1GIDlSPTyHtLAk1XOY2+FKdAHJLlam+MLSK4tHJx1c8lDWtncIMvWKOv/NbsCA2glTz5upnZwDC5d0VykPk24WfY9h4+/DmFya93Nu1RfCws5rmeVoG+Az7md+o8ogCN1PkTTVLNO6B/46jRwAeSaQbtHwq71i7hkIsnyvOOpFu9SmyO1/FqMakP60=
